### ISSUE TITLE
Cameras not being added and logs don't show reason

### ISSUE THREAD

**Issue by alivesey** [eu-evops/homebridge-hikvision#12]
I've installed the plugin and added my config, but cameras aren't added. It looks like the plugin is trying to log the reason for the cameras not adding, but can't due to its own error. Output below:

`[19/12/2020, 09:35:06] [Hikvision] Loading cameras from API
(node:1772) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:1772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by tstordyallison** [comment]
‘403’ is usually password incorrect.

Dead certain you got it right?

**Comment by alivesey** [comment]
Yes, I've copied username and password from my config directly to NVR login and get in there perfectly. I will debug a little later to see if I can track down the issue.

**Comment by alivesey** [comment]
I've switched from using a normal user on the NVR to an administrator, and it now seems to get a bit further. Error now is:

`(node:863) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at AxiosDigest.getWwwAuth (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by snapstr** [comment]
I have the same error using hoobs shell. First attempt a month ago. Saw new version, tried again and still stuck. I had been thinking I was simply not understanding the readme mention use of iOS to discover new cameras, but this matches @alivesey.

`12/23/2020, 11:45:52 AM (node:11775) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined at AxiosDigest.getWwwAuth (/home/hoobs/.hoobs/node_modules/axios-digest/index.js:67:33) at processTicksAndRejections (internal/process/task_queues.js:97:5)`

`(node:11775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by snapstr** [comment]
Similar to #2 and @Peterkrol12, I had a dud camera in my configuration and upon removing it, I got further into the initialization (past this issue). I have some other issues I'll keep working on.

**Comment by Jaco-VanderMerwe** [comment]
I have the same issue. My credentials are correct and it connects to the NVR and reads it details correctly. But then when it tries to get the cameras, the error pops up. I can't see any dud cameras in my configuration - what would this look like?  Could it be an Ezviz camera? I have 8 Hikvisions and 1 Ezviz coming into my NVR.  Or could it perhaps be ChannelZero throwing it off?

**Comment by zozo6015** [comment]
I have the same issues I am using 4 hikvision cameras with admin user with password. I can connect with no issues from the webapp but it doesn't work in here. 

```
[14/03/2021, 02:27:11] [Hikvision] Connected to NVR system: {
  DeviceInfo: {
    '$': {
      version: '1.0',
      xmlns: 'http://www.hikvision.com/ver20/XMLSchema'
    },
    deviceName: 'Network Video Recorder',
    deviceID: '48433336-3138-3435-3136-5803fb26b9b9',
    model: 'DS-7616NI-K2/16P',
    serialNumber: 'DS-7616NI-K2/16P1620180718CCRRC36184516WCVU',
    macAddress: '58:03:fb:26:b9:b9',
    firmwareVersion: 'V4.30.011',
    firmwareReleasedDate: 'build 200803',
    encoderVersion: 'V5.0',
    encoderReleasedDate: 'build 200706',
    deviceType: 'NVR',
    telecontrolID: '255'
  }
}
[14/03/2021, 02:27:11] [Hikvision] Loading cameras...
(node:8216) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:8216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by akosratku** [comment]
I had the same issue, disabling not connected channels helped me (previously I had all 8 channels on).

<img width="955" alt="Screenshot 2021-03-29 at 12 47 23" src="https://user-images.githubusercontent.com/6105511/112826221-fe3a8000-908c-11eb-84d6-e208ed56dbf2.png">

**Comment by zozo6015** [comment]
Cool, That actually worked. Thanks alot.
