### ISSUE TITLE
Error .map is not a function.

### ISSUE THREAD

**Issue by neilheyes** [eu-evops/homebridge-hikvision#16]
I'm running a DVR with the latest firmware.

I have an empty channel slot and think I've removed it from showing up.  Looking in the code though I can't see where the XML(/ISAPI/ContentMgmt/InputProxy/channels) only gives me one channel so looking like the map will fail

(node:251570) UnhandledPromiseRejectionWarning: TypeError: channels.InputProxyChannelList.InputProxyChannel.map is not a function
    at HikvisionApi.<anonymous> (/usr/lib/node_modules/@evops/homebridge-hikvision/src/HikvisionApi.ts:65:61)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/@evops/homebridge-hikvision/dist/HikvisionApi.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by neilheyes** [comment]
actually think the issue is I have 3 analogue cameras and one ip.

Do you have a link for ISAPI document and I'll have a look at the various interfaces

**Comment by sponte** [comment]
Hi @neilheyes, the IP docs can be found at https://www.use-ip.co.uk/forum/attachments/how-to-integrate-with-hikvision-lpr-function-via-isapi-pdf.2036/. And you're probably right but have a look at the API
