### ISSUE TITLE
Cannot read property 'status' of undefined  at AxiosDigest.getWwwAuth

### ISSUE THREAD

**Issue by taaa22** [eu-evops/homebridge-hikvision#2]
(node:15316) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at AxiosDigest.getWwwAuth (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.js:67:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:15316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kravena** [comment]
I was getting this error until I changed the port from 443 to port 80.

Because I don't have a certificate imported into my NVR, you can't use HTTPS connections via 443.

{
    "platform": "Hikvision",
    "host": "192.168.xxx.xxx",
    "port": 80,
    "username": "admin",
    "password": "xxxxxxxxxxxxxxx"
}

**Comment by taaa22** [comment]
Thank you for your replay, when I changed the port from 443 to 80 I get this error :

UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:12895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:12895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kravena** [comment]
Ok, I have an EZVIZ DB1 doorbell connected to my DS-7608NI-I8/8P NVR, when I remove that doorbell from the NVR, I get your same 403 error.

**Comment by taaa22** [comment]
I have DS-7108NI-Q1/8P NVR, and it is connected to 3 cameras only, with no doorbell.
My doorbell DS-KD8003-IME1 is connected directly to the DK-KH6320-WTE1.

**Comment by sponte** [comment]
Hi, firstly apologies for not responding earlier, but all github emails were going into my spam folder :(

403 error means forbidden - there is something not right with either the url or credentials. If you're familiar with `curl`, you can try:

```bash
curl -v http://nvr-ip-or-name/ISAPI -u <username>
```

This should give you more of an idea of what is happening.

**Comment by Peterkrol12** [comment]
Hi @sponte 

Firstly, thanks for the module!

I also encountered above mentioned problems and the curl returned a 401: Unauthorized. I think this was caused by only having 'digest' authentication enabled, not 'basic' authentication. After enabling 'basic' authentication I got a 404: not found from the curl command. Do you have an idea what the cause of this could be?

`curl -v http://host/ISAPI -u username
Enter host password for user 'username'
*   Trying host:80...
* Connected to host (host) port 80 (#0)
* Server auth using Basic with user 'username'
> GET /ISAPI HTTP/1.1
> Host: host
> Authorization: Basic authenticationString
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 25 Nov 2020 14:52:21 GMT
< Server: Webs
< X-Frame-Options: SAMEORIGIN
< Cache-Control: no-cache
< Content-Length: 20
< Content-Type: text/html
< Connection: keep-alive
< Keep-Alive: timeout=60, max=99
< 
* Connection #0 to host host left intact`

**Comment by tstordyallison** [comment]
^^^^ this error (the getLocalAddress one) was fixed for me via #10. So maybe that will sort it for you now you have figured out the dud camera.

**Comment by taaa22** [comment]
Thanks, @tstordyallison, and @sponte for trying to solve this issue.

Even fixed #10 doesn't solve the problem!
Any suggestions?

**Comment by farmcoding** [comment]
> Hi, firstly apologies for not responding earlier, but all github emails were going into my spam folder :(
> 
> 403 error means forbidden - there is something not right with either the url or credentials. If you're familiar with `curl`, you can try:
> 
> ```shell
> curl -v http://nvr-ip-or-name/ISAPI -u <username>
> ```
> 
> This should give you more of an idea of what is happening.

I've followed the route up to this point. Output from my curl is as follows:
> GET /ISAPI HTTP/1.1
> Host: host
> Authorization: Basic String==
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Tue, 26 Jan 2021 12:36:44 GMT
< Server: DNVRS-Webs
< Cache-Control: no-cache
< Content-Length: 138
< Content-Type: application/xml; charset="UTF-8"
< Connection: keep-alive
< Keep-Alive: timeout=60, max=99


Looks like 401 Unauthorised, but yet when I log into the NVR using the same host IP, username and password I am able to log in?

**Comment by Peterkrol12** [comment]
> ^^^^ this error (the getLocalAddress one) was fixed for me via #10. So maybe that will sort it for you now you have figured out the dud camera.

#10 Fixed my getLocalAddress error, my setup is working now, thanks everybody for the contributions!

**Comment by taaa22** [comment]
> Hi, firstly apologies for not responding earlier, but all github emails were going into my spam folder :(
> 
> 403 error means forbidden - there is something not right with either the url or credentials. If you're familiar with `curl`, you can try:
> 
> ```shell
> curl -v http://nvr-ip-or-name/ISAPI -u <username>
> ```
> 
> This should give you more of an idea of what is happening.

Hi @sponte 
When I run curl -v http://192.168.*.*/ISAPI -u admin
I got this error :

* Expire in 0 ms for 6 (transfer 0xcf7880)
*   Trying 192.168.*.*...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0xcf7880)
* Connected to 192.168.*.* (192.168.*.*) port 80 (#0)
* Server auth using Basic with user 'admin'
> GET /ISAPI HTTP/1.1
> Host: 192.168.100.3
> Authorization: Basic authenticationString
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Thu, 08 Apr 2021 22:08:25 GMT
< Server: DNVRS-Webs
< Cache-Control: no-cache
< Content-Length: 20
< Content-Type: text/html
< Connection: keep-alive
< Keep-Alive: timeout=60, max=99
< 
* Connection #0 to host 192.168.*.* left intact


When I remove ISAPI ---> curl -v http://192.168.*.* -u admin
I got this 

Enter host password for user 'admin':
* Expire in 0 ms for 6 (transfer 0x5f5880)
*   Trying 192.168.*.*...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5f5880)
* Connected to 192.168.*.* (192.168.*.*) port 80 (#0)
* Server auth using Basic with user 'admin'
> GET / HTTP/1.1
> Host: 192.168.*.*
> Authorization: Basic authenticationString
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 08 Apr 2021 22:15:21 GMT
< Server: DNVRS-Webs
< ETag: "0-5e0-1e0"
< Content-Length: 480
< Content-Type: text/html
< Connection: keep-alive
< Keep-Alive: timeout=60, max=99
< Last-Modified: Fri, 04 May 2018 06:54:42 GMT
< 
﻿<!doctype html>
<html>
<head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" >
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-cache, must-revalidate" />
        <meta http-equiv="Expires" content="0" />
</head>
<body>
</body>
<script>
        window.location.href = "/doc/page/login.asp?_" + (new Date()).getTime();
</script>
* Connection #0 to host 192.168.100.3 left intact


Is that mean anything?
