### ISSUE TITLE
i get an error, can you help?

### ISSUE THREAD

**Issue by davidjubaan** [eu-evops/homebridge-hikvision#21]
node:13217) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at AxiosDigest.getWwwAuth (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zozo6015** [comment]
I get the exact same error message when I try to connect to my DS-7616NI-K2/16P NVR with firmware version V3.4.100build 180626. Any suggestions?

**Comment by zozo6015** [comment]
In the logs I can see the following:

```
[14/03/2021, 02:27:11] [Hikvision] Connected to NVR system: {
  DeviceInfo: {
    '$': {
      version: '1.0',
      xmlns: 'http://www.hikvision.com/ver20/XMLSchema'
    },
    deviceName: 'Network Video Recorder',
    deviceID: '48433336-3138-3435-3136-5803fb26b9b9',
    model: 'DS-7616NI-K2/16P',
    serialNumber: 'DS-7616NI-K2/16P1620180718CCRRC36184516WCVU',
    macAddress: '58:03:fb:26:b9:b9',
    firmwareVersion: 'V4.30.011',
    firmwareReleasedDate: 'build 200803',
    encoderVersion: 'V5.0',
    encoderReleasedDate: 'build 200706',
    deviceType: 'NVR',
    telecontrolID: '255'
  }
}
[14/03/2021, 02:27:11] [Hikvision] Loading cameras...
(node:8216) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:8216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gowthamravichandran** [comment]
I had the same issue, this typically happens when the API call to NVR fails. 

In my case, I had to set the homebridge hikvision plugin config to use port 80 instead of 443 to get it working. 
The example config had 443 in port number. 

You can try to debug this by using a rest client like Postman tool. 
Set the `authorization` to Digest Auth and put your NVR username and password.
Make a GET call to `http://<NVR_IP_ADDRESS>:80/ISAPI/ContentMgmt/InputProxy/channels`

You should see your camera names and IP addresses in response. If not, you need to get this API working first, before you configure the homebridge plugin.
