### ISSUE TITLE
Cannot read the configuration from NVR

### ISSUE THREAD

**Issue by rpodwika** [eu-evops/homebridge-hikvision#39]
When I configured the plugin to connect to my NVR it keeps restarting with following error message

```
[21/05/2022, 23:52:21] TypeError: Cannot read properties of undefined (reading 'status')
    at AxiosDigest.getWwwAuth (/var/lib/homebridge/node_modules/.pnpm/axios-digest@0.1.1/node_modules/axios-digest/index.ts:69:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[21/05/2022, 23:52:21] TypeError: Cannot read properties of undefined (reading 'status')
    at AxiosDigest.getWwwAuth (/var/lib/homebridge/node_modules/.pnpm/axios-digest@0.1.1/node_modules/axios-digest/index.ts:69:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[21/05/2022, 23:52:21] Got SIGTERM, shutting down Homebridge...
```

not sure what's going on

**Comment by Whats-A-MattR** [comment]
Hi, 

Assuming you're following the example config, can you try with port 80 instead of 443.

**Comment by rpodwika** [comment]
Yeah I figured it out yesterday forgot to close it. The setup was for SSL and I had it disabled. I switched to 80 it worked then I switch back to 443 with https turned on and it worked too. Thanks. Now I'm having issue with it being very slow It refreshes in Home APP but I can't connect to live stream that's working LIVE.
