### ISSUE TITLE
EZVIZ DB1 Doorbell connected to NVR generates "Cannot read property 'status' of undefined"

### ISSUE THREAD

**Issue by kravena** [eu-evops/homebridge-hikvision#6]
I have a DS-7608NI-I8/8P with an EZVIZ DB1 doorbell connected wirelessly to the router, which connected to the NVR.

NVR POE address range (not visible to local network) : 192.168.254.x
Router address range : 192.168.1.x

EZVIZ DB1 : 192.168.1.147

------
[11/2/2020, 6:53:22 PM] Homebridge v1.2.3 is running on port 51656.
(node:2166) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at AxiosDigest.getWwwAuth (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
------

When I remove the DB1 this error message dissappears and is replaced with the 403 error message, which is logged elsewhere.

Does your plugin work with cameras with no web portal ?  DB1's have their web portals disabled.

**Comment by sponte** [comment]
Hi, firstly apologies for not responding earlier, but all github emails were going into my spam folder :(

Please let me know if this can be closed based on resolution from #5
