### ISSUE TITLE
getting this to work

### ISSUE THREAD

**Issue by steverae68** [eu-evops/homebridge-hikvision#8]
Hello and thank you for making this plugin.

I have it installed and it shows my 3 camera's from my NVR as expected in Homebridge, however, in homekit, im getting a no response window.

These worked perfectly in camera-ffmpeg so i know they work fine, in fact, if i have the config for camera-ffmpeg - i get 2 sets of camera's one working, one not.

what else is needed to get this working also (MOST IMPORTANT) how do you configure the motion detection to trigger ?

**Comment by sponte** [comment]
Hello

It would be hard to advise with regards to why you're getting "no response" window - some screenshots and logs would be helpful.

With regards to motion trigger though - It's quite annoying but Homekit does not enable push triggers automatically for cameras (it does for doorbells). For cameras, you need to manually enable them in your home app - check this page for more information https://support.apple.com/en-gb/HT208939

**Comment by steverae68** [comment]
Hi so the logs show that the camera's are being registered from my NVR
using this config.

        {
            "platform": "Hikvision",
            "host": "192.168.1.93",
            "port": 80,
            "username": "useraccount",
            "password": "password"
        },

[12/9/2020, 17:11:01] [Camera FFmpeg] [Front Door Camera] Snapshot requested: 1280 x 720
[12/9/2020, 17:11:01] [Camera FFmpeg] [Front Door Camera] Sending snapshot: 1280 x 720
[12/9/2020, 17:11:01] [Camera FFmpeg] [Front Door Camera] Snapshot command: /usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg -rtsp_transport tcp -re -i rtsp://username/password@192.168.1.96:554/Streaming/Channels/102 -frames:v 1 -filter:v scale='min(1280,iw)':'min(720,ih)':force_original_aspect_ratio=decrease,scale=trunc(iw/2)*2:trunc(ih/2)*2 -f image2 -
(node:13433) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getLocalAddress' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1012:27)
    at /usr/local/lib/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:969:16
    at /usr/local/lib/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:276:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:13433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:13433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    root : TTY=pts/3 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge

looks llike an issue with possibly the hap-nodejs module ?

Do the camera's need to be specified directly in the config ?

**Comment by steverae68** [comment]
Also would it make a difference if the camera's were not plugged directly into the back of the NVR but via a POE switch ? so each have a unique IP

**Comment by sponte** [comment]
Hey

The setup I've got is NVR with all cameras plugged in directly, not through PoE switch which might be the issue here. Looking at your error message here it is possible that incorrect URL is generated based on your credentials:

rtsp://__username/password__@192.168.1.96:554/Streaming/Channels/102

Perhaps you added `/` when replacing real credentials, but if you're using special characters such as `/` in your password, this might be the cause of the issue. Can you confirm you are/are not using special characters in your password?

**Comment by steverae68** [comment]
Hi,

Yes password is basic - nothing special - that rtsp link is from the camera-ffmpeg for one of my camera’s.

Is it possible to reference the camera’s individually in your plugin as you can with camera-ffmpeg.   This works fine for streaming live feed, just does not work with the motion detection from the hikvision cams so have to use third party motion sensor (Phillips) which works fine but is a bit overkill if I can get the camera itself to general the motion notification.

**Comment by steverae68** [comment]
(node:25361) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getLocalAddress' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1012:27)
    at /usr/local/lib/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:969:16
    at /usr/local/lib/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at StreamingDelegate.prepareStream (/usr/local/lib/node_modules/@evops/homebridge-hikvision/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:276:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[12/9/2020, 21:29:13] [Hikvision] [Back Camera] Stopped video stream.


This is the log when I attempt to stream from one of the camera's presented by the HikVision plugin

**Comment by sponte** [comment]
Ok, I get it. I'll look into adding debugging code so that I can investigate these issues. I'll try to do that next week. For now if you could run your homebridge with NODE_DEBUG=* and DEBUG=*, this will spit out a lot of information but might have sensitive information such as your credentials. If you comfortable providing this then I can have a look, otherwise you'll have to wait for my debugging update.

**Comment by steverae68** [comment]
Im going to attempt to connect my camera's directly to the back of my NVR as you have your set up and try again with this - really want to get native motion capture to work - if I have no joy with this I will switch the debug mode on and provide the logs you need - sorry for the delay - hope you had a fab christmas.

**Comment by steverae68** [comment]
So ho odo you get the motion detection from the camera to appear in HomeKit ?

**Comment by sponte** [comment]
Did you enable motion notifications in the home app under cameras and doorbells? There are under Home settings -> Cameras & Doorbells - you need to enable for each individual camera.

**Comment by steverae68** [comment]
Yep, did that and also enabled notifications on my phone.   Does your plugin work differently to the standard ffmpeg, does it interrogate the settings and look for the notification the dvr sends out, or do I need to do something else.   Even when I watch the motion sensor on my phone and walk in front of the camera it doesn’t activate.

What do I need to set specificially to trigger the motion on my dvr.  I know of several other plugins that hook into the email system and are triggered by that?

**Comment by sponte** [comment]
You need to have notifications enabled first in the NVR i.e. for each camera set which type of notification (motion, intrusion alert etc), and then connect it to the "Notify surveillance center" option. Have you got that set up?

**Comment by steverae68** [comment]
Hello, thanks for getting back to me.

I’ve switched to another plugin which works by detecting motion from the camera and sending a email which is picked up by the new plugin, converted to an http request which is in turn picked up by camera-ffmpeg which seems to work very well.

I could not get your plugin to respond to a motion event from the camera’s so switched to this other (more complex) method which works a treat.

I’m not sure how your plugin was determining motion and how it would trigger the camera to take a snapshot without delving into the code itself.

Thanks again for getting back to me though 👍

**Comment by sponte** [comment]
I'm sorry you couldn't get it to work - my plugin does not detect motion itself, it responds to events generated by the NVR using HTTP Event API. The relevant code for this lives at https://github.com/eu-evops/homebridge-hikvision/blob/master/src/HikvisionApi.ts#L73. 

As I said in my earlier message, you must set up notifications in the NVR configuration, perhaps below screenshot will help:

![image](https://user-images.githubusercontent.com/47468/103291461-af287480-49e3-11eb-9db9-18708b35b3c3.png)

**Comment by tstordyallison** [comment]
(Makes me think this should probably be copy and pasted to the README! I had to mess around a bit to find out it was that option).

**Comment by steverae68** [comment]
So it responds generates an http request when the Notification Center triggers.... so this is then picked up by the camera-ffmpeg http system which can then be used to trigger the event.

This was not made at all clear in the documentation.   

I will revisit this at some point this week - if this works purely based on the Notification Center trigger which activates the recording in the HikVision app itself without the need for any further configuration / plugin ,this would be brill.

Detailed description of what call this makes and what port needs to be opened within the camera-ffmpeg http side would also be useful

**Comment by sponte** [comment]
I'll update the README to reflect that :) Pull requests welcome too :)
